name: R-lib actions
run-name: ${{ github.actor }} is testing out r-lib Actions
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  Explore-r-lib-Actions:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: '3.5.3' # The R version to download (if necessary) and use.
    - run: Rscript -e 'print("hello")'
